#!/usr/bin/env bash
#
# Linux WAN failover script.
#
# Copyright 2010 Louwrentius
#
# Licence = GNU GPL
#

VERSION=1.20
CONFIG=/etc/wfs.conf

if [ -e "$CONFIG" ]
then
    . $CONFIG
else
    TARGET_FILE="targets.txt"
    TARGETS=`cat "$TARGET_FILE"`
    PRIMARY_GW=10.0.0.1
    SECONDARY_GW=10.0.0.200
    INTERVAL=25
    COUNT=2
    DISTANCE=15
    THRESHOLD=3
    COOLDOWNDELAY=20
    MAIL_TARGET=""
    DAEMON=1
    PIDFILE=/var/run/wfs.pid
fi

TARGET_FAILED=0
ACTIVE_CONNECTION=""

#
# If some command must be run after a failover or restore, please specify
# the commands within these variables.
#
PRIMARY_CMD=""
SECONDARY_CMD=""

# --- do not change anything below ---


route -n | grep -w "$PRIMARY_GW" | grep -w "0.0.0.0" >> /dev/null 2>&1
if [ "$?" == "0" ]
then
    ACTIVE_CONNECTION=PRIMARY
else
    ACTIVE_CONNECTION=SECONDARY
fi

log2dsply () {
    
    if [ "$QUIET" == "0" ]
    then
        echo "$1" 
    fi
}

log2mail () {

    SUBJECT="$1"
    BODY="$2"
    if [ ! -z "$MAIL_TARGET" ]
    then
        echo "$BODY" | mail -s "$SUBJECT" "$MAIL_TARGET" &
    fi
}

log2syslog () {

    echo "$1" | logger
}


if [ -e "$PIDFILE" ]
then
    log2dsply "PID file $PIDFILE exists. Aborting."
    log2syslog "PID file $PIDFILE exists. Aborting"
    exit 1
fi

route_del () {

    route del default gw "$1"
}

if [ "$DEBUG" == "1" ]
then
    log2dsply "Currently active WAN link: $ACTIVE_CONNECTION"
fi

#
# This route allows testing if the failed primary link
# Is available again, when in failover mode.
#
route add -host "$PRIMARY_TARGET" gw "$PRIMARY_GW" >> /dev/null 2>&1
route add -host "$SECONDARY_TARGET" gw "$PRIMARY_GW" >> /dev/null 2>&1

test_single_target () {

    TARGET="$1"

    ping -c "$COUNT" "$TARGET" >> /dev/null 2>&1
    if [ ! "$?" == "0" ]
    then
        if [ "$DEBUG" == "1" ]
        then
            log2dsply "Host $HOST UNREACHABLE"
            log2syslog "Host $HOST UNREACHABLE"
        fi

        ((TARGET_FAILED++)) 
        DISTANCE=5

    else
        if [ "$TARGET_FAILED" -gt "0" ] 
        then
            ((TARGET_FAILED--))

        if [ "$DEBUG" == "1" ]
        then
            log2dsply "Host $TARGET OK"
            log2syslog "Host $TARGET OK"
        fi
    fi

}


test_wan_status () {

    for x in $TARGETS
    do
        test_single_target $x
        check_wan_status
        sleep "$DISTANCE"
    done
}


route_add () {

    route add default gw "$1"
}

switch_to_primary () {

    route_del "$SECONDARY_GW"
    route_add "$PRIMARY_GW"
    ACTIVE_CONNECTION="PRIMARY"
}

switch_to_secondary () {

    route_del "$PRIMARY_GW"
    route_add "$SECONDARY_GW"
    ACTIVE_CONNECTION="SECONDARY"
}

check_wan_status () {

    if [ "$TARGET_FAILED" -ge "$THRESHOLD" ] && [ "$ACTIVE_CONNECTION" == "PRIMARY" ]
    then
        MSG="Primary WAN link failed. Switched to secondary link."
        BODY=`route -n`
        log2mail "$MSG" "$BODY"
        log2dsply "$MSG"
        log2syslog "$MSG"
        switch
    elif [ "$ACTIVE_CONNECTION" == "SECONDARY" ] 
    then
        if [ "$TARGET_FAILED" == "0" ] 
        then
            MSG="Primary WAN link OK. Switched back to primary link."
            BODY=`route -n`
            log2mail "$MSG" "$BODY"
            log2dsply "$MSG"
            log2syslog "$MSG"
            switch
        fi
    else
        if [ "$DEBUG" = "1" ]
        then
            log2dsply "WAN Link: $ACTIVE_CONNECTION"
            log2syslog "WAN Link: $ACTIVE_CONNECTION"
        fi
    fi
}

switch () {

    if [ "$ACTIVE_CONNECTION" == "PRIMARY" ]
    then
        switch_to_secondary
        if [ ! -z "$SECONDARY_CMD" ]
        then
            eval "$SECONDARY_CMD"
        fi
    elif [ "$ACTIVE_CONNECTION" == "SECONDARY" ]
    then
        switch_to_primary
        if [ ! -z "$PRIMARY_CMD" ]
        then
            eval "$PRIMARY_CMD"
        fi
    fi
    sleep "$COOLDOWNDELAY"
}

start_wfs () {

    while true
    do
        test_wan_status
        sleep "$INTERVAL"
    done
}

if [ "$DAEMON" == "0" ]
then
    log2dsply "* Starting monitoring of WAN link. *"
    log2syslog "*** Starting monitoring of WAN link. ***"
    start_wfs
else
    log2syslog "*** Starting monitoring of WAN link. ***"
    start_wfs &
    echo "$!" > "$PIDFILE"
fi
    




